/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    visitors: VisitorAuthOperations;
  };
  blocks: {};
  collections: {
    disciplines: Discipline;
    'work-samples': WorkSample;
    enquiries: Enquiry;
    pages: Page;
    media: Media;
    users: User;
    visitors: Visitor;
    'visitor-sessions': VisitorSession;
    'login-codes': LoginCode;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    disciplines: DisciplinesSelect<false> | DisciplinesSelect<true>;
    'work-samples': WorkSamplesSelect<false> | WorkSamplesSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    visitors: VisitorsSelect<false> | VisitorsSelect<true>;
    'visitor-sessions': VisitorSessionsSelect<false> | VisitorSessionsSelect<true>;
    'login-codes': LoginCodesSelect<false> | LoginCodesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Visitor;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface VisitorAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Направления работы (музыка, видео, 3D, гитары…). Список открыт для роста.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disciplines".
 */
export interface Discipline {
  id: string;
  name: string;
  /**
   * Латиницей, через дефис. Используется в адресе страницы.
   */
  slug: string;
  /**
   * Короткая фраза для карточки на главной.
   */
  strapline: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tone: 'live' | 'digital';
  order: number;
  published?: boolean | null;
  coverImage?: (string | null) | Media;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Фотографии для сайта. Текст «alt» обязателен для доступности.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Опишите изображение — это обязательно для доступности.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    gallery?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Примеры работ внутри направления.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-samples".
 */
export interface WorkSample {
  id: string;
  title: string;
  discipline: string | Discipline;
  description: string;
  image?: (string | null) | Media;
  externalVideoUrl?: string | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Заявки с сайта. Статус меняется здесь; проблемы с доставкой видны в колонке справа.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: string;
  name: string;
  /**
   * Адрес для входа на сайт. Заявки без этого поля не видны посетителю. Ответ без адреса никому не отправляется.
   */
  submitterEmail?: string | null;
  preferredContactMethod: string;
  desiredDate?: string | null;
  jobDescription: string;
  discipline: string | Discipline;
  status?: ('new' | 'in_progress' | 'closed') | null;
  submittedAt?: string | null;
  /**
   * Виден посетителю после входа. Если у заявки нет email, уведомление не отправляется.
   */
  ownerReply?: string | null;
  replyNotifiedAt?: string | null;
  /**
   * Заполняется автоматически при создании заявки.
   */
  delivery?: {
    email?: {
      status?: ('sent' | 'failed' | 'disabled') | null;
      attemptedAt?: string | null;
      error?: string | null;
    };
    telegram?: {
      status?: ('sent' | 'failed' | 'disabled') | null;
      attemptedAt?: string | null;
      error?: string | null;
    };
    visitorAck?: {
      status?: ('sent' | 'failed' | 'disabled') | null;
      attemptedAt?: string | null;
      error?: string | null;
    };
    replyNotice?: {
      status?: ('sent' | 'failed' | 'disabled') | null;
      attemptedAt?: string | null;
      error?: string | null;
    };
  };
  /**
   * Автоматический флаг — хотя бы один канал не сработал.
   */
  deliveryFailed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Обычные страницы сайта. Скрытая страница «Друзья» — одна из них.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  /**
   * Главы — заголовок, текст, фотографии.
   */
  chapters?:
    | {
        heading?: string | null;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        photos?: (string | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  published?: boolean | null;
  /**
   * Выключите для страниц вне навигации (например, «Друзья»).
   */
  showInNav?: boolean | null;
  /**
   * Выключите, чтобы страница не попадала в sitemap.xml.
   */
  includeInSitemap?: boolean | null;
  /**
   * Включите, чтобы запретить индексацию поисковиками.
   */
  noindex?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Владелец сайта. Один аккаунт — регистрация закрыта.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Адреса, которые входили на сайт. Удаление последней заявки с этим адресом удаляет и запись здесь.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitors".
 */
export interface Visitor {
  id: string;
  email: string;
  firstSeenAt?: string | null;
  lastSignedInAt?: string | null;
  activeSessionCount?: number | null;
  /**
   * Последнее известное состояние блокировки (только для отображения).
   */
  blockedUntil?: string | null;
  /**
   * Немедленно завершает все активные сессии на всех устройствах.
   */
  revokeAllSessions?: boolean | null;
  updatedAt: string;
  createdAt: string;
  collection: 'visitors';
}
/**
 * Сессии входа — по одной на устройство. Отзыв — через список посетителей.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitor-sessions".
 */
export interface VisitorSession {
  id: string;
  visitor: string | Visitor;
  tokenHash: string;
  sessionStartedAt: string;
  expiresAt: string;
  revokedAt?: string | null;
  endedReason?: ('signed_out' | 'revoked_by_owner' | 'identity_removed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-codes".
 */
export interface LoginCode {
  id: string;
  visitor: string | Visitor;
  codeHash: string;
  issuedAt: string;
  expiresAt: string;
  consumedAt?: string | null;
  supersededAt?: string | null;
  attemptCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'disciplines';
        value: string | Discipline;
      } | null)
    | ({
        relationTo: 'work-samples';
        value: string | WorkSample;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: string | Enquiry;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'visitors';
        value: string | Visitor;
      } | null)
    | ({
        relationTo: 'visitor-sessions';
        value: string | VisitorSession;
      } | null)
    | ({
        relationTo: 'login-codes';
        value: string | LoginCode;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'visitors';
        value: string | Visitor;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'visitors';
        value: string | Visitor;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disciplines_select".
 */
export interface DisciplinesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  strapline?: T;
  description?: T;
  tone?: T;
  order?: T;
  published?: T;
  coverImage?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-samples_select".
 */
export interface WorkSamplesSelect<T extends boolean = true> {
  title?: T;
  discipline?: T;
  description?: T;
  image?: T;
  externalVideoUrl?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  submitterEmail?: T;
  preferredContactMethod?: T;
  desiredDate?: T;
  jobDescription?: T;
  discipline?: T;
  status?: T;
  submittedAt?: T;
  ownerReply?: T;
  replyNotifiedAt?: T;
  delivery?:
    | T
    | {
        email?:
          | T
          | {
              status?: T;
              attemptedAt?: T;
              error?: T;
            };
        telegram?:
          | T
          | {
              status?: T;
              attemptedAt?: T;
              error?: T;
            };
        visitorAck?:
          | T
          | {
              status?: T;
              attemptedAt?: T;
              error?: T;
            };
        replyNotice?:
          | T
          | {
              status?: T;
              attemptedAt?: T;
              error?: T;
            };
      };
  deliveryFailed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  chapters?:
    | T
    | {
        heading?: T;
        body?: T;
        photos?: T;
        id?: T;
      };
  published?: T;
  showInNav?: T;
  includeInSitemap?: T;
  noindex?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        gallery?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitors_select".
 */
export interface VisitorsSelect<T extends boolean = true> {
  email?: T;
  firstSeenAt?: T;
  lastSignedInAt?: T;
  activeSessionCount?: T;
  blockedUntil?: T;
  revokeAllSessions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitor-sessions_select".
 */
export interface VisitorSessionsSelect<T extends boolean = true> {
  visitor?: T;
  tokenHash?: T;
  sessionStartedAt?: T;
  expiresAt?: T;
  revokedAt?: T;
  endedReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-codes_select".
 */
export interface LoginCodesSelect<T extends boolean = true> {
  visitor?: T;
  codeHash?: T;
  issuedAt?: T;
  expiresAt?: T;
  consumedAt?: T;
  supersededAt?: T;
  attemptCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Текст и фото главной страницы.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  name: string;
  /**
   * Одна фраза, например: «Я играю, снимаю, паяю, строю».
   */
  essenceSentence: string;
  aboutPhoto?: (string | null) | Media;
  /**
   * 2–3 абзаца биографии.
   */
  bioParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Показывается в подтверждении после отправки заявки.
   */
  replyWindowCopy: string;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Общие настройки сайта.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  /**
   * Куда приходят уведомления о заявках (обязательный канал).
   */
  ownerNotificationEmail: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  name?: T;
  essenceSentence?: T;
  aboutPhoto?: T;
  bioParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  replyWindowCopy?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  ownerNotificationEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}